# Generated by Django 4.1.6 on 2023-04-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pfp',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
