# Generated by Django 4.1.6 on 2023-04-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.CharField(blank=True, default='/static/imgs/pets/0.png', max_length=100, null=True),
        ),
    ]
