# Generated by Django 4.2.23 on 2025-08-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_profile_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pfp',
            field=models.CharField(blank=True, default='/static/imgs/pets/0.svg', max_length=100, null=True),
        ),
    ]
